import math
print("Hello")
print("Q1")
lado = float(input("Insira o valor do lado \n"))
print("Area vale", lado*lado)
print("Q2")
print("Perimetro vale", lado*4)
print("Q3")
base = float(input("Insira o valor da base \n"))
altura = float(input("Insira o valor da altura \n"))
print("Area do retangulo vale", base*altura)
print("Perimetro do retangulo vale", (base*2)+ (altura*2))
print("Q4")
coA = float(input("Insira o valor do coeficiente A \n"))
coB = float(input("Insira o valor do coeficiente B \n"))
coC = float(input("Insira o valor do coeficiente C \n"))
print("Delta vale", (coB**2)-(4*coA*coC))
print("Q5")
raio = float(input("Insira o valor do raio \n"))
print("Comprimento da circunferencia vale", 2*raio*math.pi)
print("Q6")
print("Area da circunferencia vale", raio**2*math.pi)
print("Q7")
cateto1 = float(input("Insira o valor da cateto1 \n"))
cateto2 = float(input("Insira o valor da cateto2 \n"))
hipo = (cateto1**2 + cateto2**2)
print("Hipotenusa vale", math.sqrt(hipo))
print("Q8")
x1 = float(input("Insira o valor de x1 \n"))
x2 = float(input("Insira o valor de x2 \n"))
y1 = float(input("Insira o valor de y1 \n"))
y2 = float(input("Insira o valor de y2 \n"))
dist = (math.pow(x2-x1,2))+ (math.pow(y2-y1,2))
print("Hipotenusa vale", math.sqrt(dist))

